"""Database models and repositories for Signal Observatory."""

from observatory_db.arxiv_models import (
    ArxivAuthor,
    ArxivCategory,
    ArxivCollectionCursor,
    ArxivPaper,
    ArxivPaperAuthor,
    ArxivPaperCategory,
    ArxivPaperObservation,
    ArxivRawResponse,
    ArxivTopicMatch,
)
from observatory_db.base import Base
from observatory_db.coverage_models import CoverageStatus, CoverageStrategy, TopicSourceCoverage
from observatory_db.github_models import (
    GithubDiscoveryState,
    GithubRawResponse,
    GithubRepository,
    GithubRepositoryPollState,
    GithubRepositorySnapshot,
    GithubTopicRepositoryMatch,
)
from observatory_db.models import (
    DataQualityCheck,
    IngestionError,
    IngestionRun,
    SchedulerExecution,
    SchedulerExecutionStatus,
    Source,
    Topic,
    TopicAlias,
    TopicCategory,
    TopicRegistryAuditLog,
    TopicRegistryVersion,
    TopicSourceMapping,
)

__all__ = [
    "Base",
    "ArxivAuthor",
    "ArxivCategory",
    "ArxivCollectionCursor",
    "ArxivPaper",
    "ArxivPaperAuthor",
    "ArxivPaperCategory",
    "ArxivPaperObservation",
    "ArxivRawResponse",
    "ArxivTopicMatch",
    "DataQualityCheck",
    "CoverageStatus",
    "CoverageStrategy",
    "GithubDiscoveryState",
    "GithubRawResponse",
    "GithubRepository",
    "GithubRepositoryPollState",
    "GithubRepositorySnapshot",
    "GithubTopicRepositoryMatch",
    "IngestionError",
    "IngestionRun",
    "SchedulerExecution",
    "SchedulerExecutionStatus",
    "Source",
    "Topic",
    "TopicAlias",
    "TopicCategory",
    "TopicRegistryAuditLog",
    "TopicRegistryVersion",
    "TopicSourceMapping",
    "TopicSourceCoverage",
]
