import type {
  ArxivStatus,
  Category,
  GithubStatus,
  CoverageItem,
  CoverageListResponse,
  OperationsOverview,
  RegistryStatus,
  SourceMapping,
  Topic,
  TopicDevelopment,
  TopicCoverage,
  TopicResearch,
} from "../types/api";

export const categories: Category[] = [
  {
    id: "category-ai",
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    description: "AI research, systems and operations.",
    parent: null,
    sort_order: 10,
  },
  {
    id: "category-ai-systems",
    name: "AI Systems",
    slug: "ai-systems",
    description: "Applied AI systems.",
    parent: "artificial-intelligence",
    sort_order: 11,
  },
  {
    id: "category-software",
    name: "Software Development",
    slug: "software-development",
    description: "Software ecosystems.",
    parent: null,
    sort_order: 20,
  },
  {
    id: "category-data",
    name: "Data Systems",
    slug: "data-systems",
    description: "Data technologies.",
    parent: null,
    sort_order: 30,
  },
];

export const registryStatus: RegistryStatus = {
  version: 1,
  checksum: "a".repeat(64),
  last_synced_at: "2026-08-09T11:26:24Z",
  topic_count: 101,
  active_topics: 101,
  alias_count: 109,
  source_mapping_count: 204,
  warnings: 0,
};

export const arxivStatus: ArxivStatus = {
  source: "arxiv",
  enabled: true,
  collector_state: "not_initialized",
  last_run_at: null,
  last_successful_run_at: null,
  last_run_status: null,
  tracked_topics: 1,
  tracked_mappings: 1,
  papers_observed: 0,
  last_24h_new_papers: 0,
  error_count_last_run: 0,
};

export const githubStatus: GithubStatus = {
  source: "github",
  enabled: true,
  auth_configured: false,
  collector_state: "not_configured",
  last_run_at: null,
  last_run_status: null,
  last_discovery_at: null,
  last_snapshot_at: null,
  last_successful_snapshot_at: null,
  tracked_repositories: 0,
  snapshots: 0,
  errors_last_run: 0,
  search_rate: null,
  core_rate: null,
};

export const topicResearch: TopicResearch = {
  topic: {
    slug: "model-context-protocol",
    canonical_name: "Model Context Protocol",
  },
  source: "arxiv",
  state: "not_initialized",
  last_observed_at: null,
  collector_error: null,
  summary: {
    papers_total: 0,
    papers_7d: 0,
    papers_30d: 0,
    unique_authors_30d: 0,
  },
  latest_papers: [],
};

export const liveTopicResearch: TopicResearch = {
  ...topicResearch,
  state: "live",
  last_observed_at: "2026-08-09T06:30:00Z",
  summary: {
    papers_total: 12,
    papers_7d: 3,
    papers_30d: 8,
    unique_authors_30d: 17,
  },
  latest_papers: [
    {
      arxiv_id: "2608.01234",
      title: "Reliable Context Exchange for Agentic Systems",
      authors: ["Ada Example", "Lin Researcher"],
      published_at: "2026-08-08T12:00:00Z",
      updated_at: "2026-08-09T06:30:00Z",
      primary_category: "cs.AI",
      categories: ["cs.AI", "cs.SE"],
      abstract:
        "A persisted example abstract used to verify the Research surface.",
      abs_url: "https://arxiv.org/abs/2608.01234",
      matched_query: 'all:"model context protocol"',
      source_mapping_id: "mapping-arxiv-mcp",
      ingestion_run_id: "run-1",
      raw_checksum: "b".repeat(64),
    },
  ],
};

export const topicDevelopment: TopicDevelopment = {
  topic: {
    slug: "model-context-protocol",
    canonical_name: "Model Context Protocol",
  },
  source: "github",
  state: "not_initialized",
  last_snapshot_at: null,
  last_successful_snapshot_at: null,
  collector_error: null,
  summary: {
    repositories_tracked: 0,
    stars_total: 0,
    forks_total: 0,
    repositories_pushed_30d: 0,
    stars_delta_since_previous_snapshot: null,
    forks_delta_since_previous_snapshot: null,
    previous_snapshot_at: null,
    latest_snapshot_at: null,
  },
  top_repositories: [],
};

export const liveTopicDevelopment: TopicDevelopment = {
  ...topicDevelopment,
  state: "live",
  last_snapshot_at: "2026-08-11T03:00:00Z",
  last_successful_snapshot_at: "2026-08-11T03:01:00Z",
  summary: {
    repositories_tracked: 6,
    stars_total: 12500,
    forks_total: 980,
    repositories_pushed_30d: 5,
    stars_delta_since_previous_snapshot: 42,
    forks_delta_since_previous_snapshot: 7,
    previous_snapshot_at: "2026-08-10T03:00:00Z",
    latest_snapshot_at: "2026-08-11T03:00:00Z",
  },
  top_repositories: [
    {
      github_repository_id: 123456,
      full_name: "modelcontextprotocol/servers",
      description: "Reference servers for the Model Context Protocol.",
      html_url: "https://github.com/modelcontextprotocol/servers",
      language: "TypeScript",
      stars: 10000,
      forks: 800,
      pushed_at: "2026-08-11T01:00:00Z",
      archived: false,
      disabled: false,
      latest_snapshot_at: "2026-08-11T03:00:00Z",
      previous_snapshot_at: "2026-08-10T03:00:00Z",
      stars_delta: 40,
      forks_delta: 6,
      match_evidence: [
        {
          matched_query: '"model context protocol" in:name,description,readme',
          source_mapping_id: "mapping-github-mcp",
          discovery_rank: 1,
          discovery_run_id: "run-github-1",
          raw_checksum: "c".repeat(64),
        },
      ],
    },
  ],
};

export const researchCoverage: CoverageItem = {
  topic: {
    id: "mcp",
    slug: "model-context-protocol",
    canonical_name: "Model Context Protocol",
  },
  source: "arxiv",
  coverage_status: "partial",
  coverage_strategy: "historical_backfill",
  coverage_start: "2026-07-01",
  coverage_end: "2026-08-01",
  target_start: "2026-07-01",
  target_end: "2026-08-11",
  first_observed_at: "2026-08-10T03:00:00Z",
  last_observed_at: "2026-08-11T03:00:00Z",
  last_successful_run_at: "2026-08-10T03:00:00Z",
  observation_count: 12,
  expected_observation_count: null,
  missing_observation_count: 1,
  partial_reason: "One historical cursor window remains incomplete.",
  freshness: "fresh",
  derived_at: "2026-08-11T04:00:00Z",
  derivation_version: "coverage-v1",
  metadata: { partial_mapping_count: 1 },
};

export const developerCoverage: CoverageItem = {
  ...researchCoverage,
  source: "github",
  coverage_status: "forward_only",
  coverage_strategy: "forward_snapshot",
  coverage_start: "2026-08-11",
  coverage_end: "2026-08-11",
  target_start: null,
  target_end: null,
  first_observed_at: "2026-08-11T03:00:00Z",
  last_successful_run_at: "2026-08-11T03:00:00Z",
  observation_count: 1,
  expected_observation_count: 1,
  missing_observation_count: 0,
  partial_reason: null,
  metadata: { historical_backfill: "unavailable_by_design" },
};

export const coverageList: CoverageListResponse = {
  items: [researchCoverage, developerCoverage],
  total: 2,
  limit: 1000,
  offset: 0,
  generated_at: "2026-08-11T04:00:00Z",
  derivation_version: "coverage-v1",
};

export const topicCoverage: TopicCoverage = {
  topic: {
    slug: "model-context-protocol",
    canonical_name: "Model Context Protocol",
  },
  channels: [
    {
      channel: "research",
      label: "Research",
      source: "arxiv",
      collection_state: "collecting",
      coverage: researchCoverage,
    },
    {
      channel: "developer",
      label: "Developer",
      source: "github",
      collection_state: "collecting",
      coverage: developerCoverage,
    },
    {
      channel: "community",
      label: "Community",
      source: "hacker_news",
      collection_state: "not_started",
      coverage: null,
    },
    {
      channel: "public",
      label: "Public",
      source: "wikipedia",
      collection_state: "not_started",
      coverage: null,
    },
  ],
  generated_at: "2026-08-11T04:00:00Z",
};

export const operationsOverview: OperationsOverview = {
  overall_state: "degraded",
  explanation:
    "Research is degraded. Developer is healthy. 1 Topic-source coverage projection is partial.",
  registry: { state: "healthy", version: 1, warnings: 0 },
  sources: [
    {
      source: "arxiv",
      channel: "research",
      label: "Research",
      display_name: "arXiv",
      implemented: true,
      enabled: true,
      collector_state: "degraded",
      last_run_at: "2026-08-11T03:00:00Z",
      last_successful_run_at: "2026-08-10T03:00:00Z",
      latest_run_status: "partial",
      active_mappings: 42,
      failed_mappings: 2,
      partial_mappings: 3,
      stale_mappings: 0,
      errors_last_run: 2,
      raw_responses_last_run: 47,
      freshness: "fresh",
      details: { papers_observed: 680 },
    },
    {
      source: "github",
      channel: "developer",
      label: "Developer",
      display_name: "GitHub",
      implemented: true,
      enabled: true,
      collector_state: "healthy",
      last_run_at: "2026-08-11T03:00:00Z",
      last_successful_run_at: "2026-08-11T03:00:00Z",
      latest_run_status: "succeeded",
      active_mappings: 54,
      failed_mappings: 0,
      partial_mappings: 0,
      stale_mappings: 0,
      errors_last_run: 0,
      raw_responses_last_run: 51,
      freshness: "fresh",
      details: {
        tracked_repositories: 51,
        snapshot_dates: 1,
        latest_snapshot: "2026-08-11",
      },
    },
    ...(["hacker_news", "wikipedia"] as const).map((source) => ({
      source,
      channel: source === "hacker_news" ? "community" : "public",
      label: source === "hacker_news" ? "Community" : "Public",
      display_name: source === "hacker_news" ? "Hacker News" : "Wikipedia",
      implemented: false,
      enabled: true,
      collector_state: "not_initialized",
      last_run_at: null,
      last_successful_run_at: null,
      latest_run_status: null,
      active_mappings: 1,
      failed_mappings: 0,
      partial_mappings: 0,
      stale_mappings: 0,
      errors_last_run: 0,
      raw_responses_last_run: 0,
      freshness: "unknown",
      details: { collection_state: "not_started" },
    })),
  ],
  coverage_summary: {
    complete: 2,
    partial: 1,
    forward_only: 1,
    empty: 0,
    unknown: 0,
  },
  data_quality: {
    ingestion_errors_last_24h: 2,
    partial_mappings: 3,
    stale_cursors: 0,
    missing_snapshot_dates: 0,
    raw_checksum_failures: null,
    raw_integrity_state: "not_verified",
    registry_warnings: 0,
    scheduler_missed_last_24h: 0,
    scheduler_interrupted_last_24h: 0,
    scheduler_partial_last_24h: 0,
    scheduler_failed_last_24h: 0,
    scheduler_late_last_24h: 0,
  },
  scheduler: {
    job_name: "arxiv_daily",
    source_name: "arxiv",
    schedule: "0 2 * * *",
    on_time_threshold_seconds: 300,
    continuity_state: "passed",
    continuity_days_required: 7,
    continuity_windows_observed: 7,
    continuity_missing: [],
    continuity_duplicates: 0,
    continuity_missed_or_interrupted: 0,
    punctuality_state: "pending",
    qualification_contract: "scheduler-punctuality-v2",
    qualification_start: "2026-08-12T02:00:00Z",
    qualification_required: 3,
    qualification_completed: 0,
    qualification_on_time: 0,
    qualification_late: 0,
    qualification_missed: 0,
    qualification_interrupted: 0,
    qualification_missing: [],
    qualification_duplicates: 0,
    next_qualification_window: "2026-08-12T02:00:00Z",
    latest_execution: {
      execution_id: "scheduler-1",
      scheduled_at: "2026-08-11T02:00:00Z",
      started_at: "2026-08-11T02:08:00Z",
      finished_at: "2026-08-11T03:00:00Z",
      dispatch_delay_seconds: 480,
      timing_state: "late",
      collector_status: "partial",
      error_type: "collector_partial",
    },
    evidence: [],
    status: "pending",
    exit_code: 1,
    message: "Post-deployment punctuality qualification is still accumulating.",
    modified_records: 0,
  },
  data_protection: {
    latest_backup: {
      backup_id: "20260811T050000Z-a1b2c3",
      label: "E04.5B acceptance",
      completed_at: "2026-08-11T05:00:00Z",
      verification_state: "pass",
      migration_head: "20260812_0006",
      database_size_bytes: 12582912,
      raw_objects: 98,
      raw_size_bytes: 5242880,
      total_backup_bytes: 17825792,
      registry_version: 1,
    },
    latest_verified_backup: {
      backup_id: "20260811T050000Z-a1b2c3",
      label: "E04.5B acceptance",
      completed_at: "2026-08-11T05:00:00Z",
      verification_state: "pass",
      migration_head: "20260812_0006",
      database_size_bytes: 12582912,
      raw_objects: 98,
      raw_size_bytes: 5242880,
      total_backup_bytes: 17825792,
      registry_version: 1,
    },
    latest_verified_backup_age_seconds: 82800,
    latest_restore_drill: {
      backup_id: "20260811T050000Z-a1b2c3",
      restore_completed_at: "2026-08-11T05:08:00Z",
      result: "pass",
      duration_ms: 8500,
    },
  },
  generated_at: "2026-08-11T04:00:00Z",
};

function sourceMapping(source: string): SourceMapping {
  return {
    source,
    enabled: true,
    mapping_type: "registry",
    external_identifier: source === "wikipedia" ? "Example page" : null,
    query: source === "arxiv" ? "example topic" : null,
    configuration:
      source === "github"
        ? { search_queries: ["example/topic"] }
        : source === "hacker_news"
          ? { terms: ["Example Topic"] }
          : source === "wikipedia"
            ? { page_titles: ["Example Topic"] }
            : { search_terms: ["example topic"] },
  };
}

export function makeTopic(
  index: number,
  overrides: Partial<Topic> = {},
): Topic {
  const categoryCycle = ["ai-systems", "software-development", "data-systems"];
  return {
    topic_id: `topic-${index}`,
    canonical_name: `Topic ${String(index).padStart(2, "0")}`,
    slug: `topic-${index}`,
    description: `A durable description for monitored technology topic ${index}.`,
    category: categoryCycle[index % categoryCycle.length],
    status: "active",
    monitoring_priority: 100 - index,
    deprecated_at: null,
    registry_version: 1,
    metadata: {},
    aliases: [
      {
        value: `T${index}`,
        normalized_alias: `t${index}`,
        type: "abbreviation",
        match_mode: "exact",
        case_sensitive: false,
        status: "active",
        confidence: 1,
        metadata: {},
      },
    ],
    sources: [sourceMapping("arxiv"), sourceMapping("wikipedia")],
    ...overrides,
  };
}

export const modelContextProtocol = makeTopic(200, {
  topic_id: "mcp",
  canonical_name: "Model Context Protocol",
  slug: "model-context-protocol",
  description:
    "An open protocol connecting AI applications to tools and contextual data sources.",
  category: "ai-systems",
  monitoring_priority: 98,
  aliases: [
    {
      value: "MCP",
      normalized_alias: "MCP",
      type: "abbreviation",
      match_mode: "exact",
      case_sensitive: true,
      status: "active",
      confidence: 1,
      metadata: {},
    },
    {
      value: "MCP server",
      normalized_alias: "MCP server",
      type: "search_term",
      match_mode: "phrase",
      case_sensitive: true,
      status: "active",
      confidence: 1,
      metadata: {},
    },
  ],
  sources: [
    sourceMapping("arxiv"),
    sourceMapping("github"),
    sourceMapping("hacker_news"),
    sourceMapping("wikipedia"),
  ],
});
